;/*FB_PKG_DELIM*/

__d("BaseMenuFocusGroup",["fbt","CometComponentWithKeyCommands.react","CometKeys","FocusGroup.react","focusScopeQueries","react"],(function(t,n,r,o,a,i,l,s){"use strict";var e=["useKeyCommands"],u,c=u||(u=o("react")),d=o("FocusGroup.react").createFocusGroup(o("focusScopeQueries").tabbableScopeQuery),m=d[0],p=d[1];function _(t){var n=t.useKeyCommands,o=n===void 0?!0:n,a=babelHelpers.objectWithoutPropertiesLoose(t,e);if(!o)return c.jsx(m,babelHelpers.extends({},a));var i=[{command:{key:r("CometKeys").UP},description:s._(/*BTDS*/"Previous item"),handler:function(){}},{command:{key:r("CometKeys").DOWN},description:s._(/*BTDS*/"Next item"),handler:function(){}}];return c.jsx(r("CometComponentWithKeyCommands.react"),{commandConfigs:i,children:c.jsx(m,babelHelpers.extends({},a))})}_.displayName=_.name+" [from "+i.id+"]";var f={FocusGroup:_,FocusItem:p};l.default=f}),226);
__d("BillingPlatformContext",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=s.createContext("desktop"),c=u;l.default=c}),98);
__d("BillingPlatformContextProvider",["BillingPlatformContext","react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react"));function u(e){var t=e.children,n=e.platform;return s.jsx(r("BillingPlatformContext").Provider,{value:n,children:t})}u.displayName=u.name+" [from "+i.id+"]",l.default=u}),98);
__d("BillingSurfaceLoggingContext",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=s.createContext(),c=u;l.default=c}),98);
__d("MetaBrandCaretDownFilled24Icon.react",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react"));function u(e){return s.jsxs("svg",babelHelpers.extends({viewBox:"0 0 24 24",fill:"currentColor",width:"1em",height:"1em"},e,{children:[e.title!=null&&s.jsx("title",{children:e.title}),e.children!=null&&s.jsx("defs",{children:e.children}),s.jsx("path",{fillRule:"evenodd",clipRule:"evenodd",d:"M4.341 7.247a1 1 0 0 0-.094 1.412l7 8a1 1 0 0 0 1.506 0l7-8a1 1 0 0 0-1.506-1.318L12 14.482l-6.247-7.14a1 1 0 0 0-1.412-.094z"})]}))}u.displayName=u.name+" [from "+i.id+"]",u._isSVG=!0;var c=u;l.default=c}),98);
__d("MetaBrandCheckmarkSquareFilled24Icon.react",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react"));function u(e){return s.jsxs("svg",babelHelpers.extends({viewBox:"0 0 24 24",fill:"currentColor",width:"1em",height:"1em"},e,{children:[e.title!=null&&s.jsx("title",{children:e.title}),e.children!=null&&s.jsx("defs",{children:e.children}),s.jsx("path",{d:"m17.214 10.592-.64-.768.64.768.066-.056a2 2 0 0 0-2.56-3.072l-.067.055a44.003 44.003 0 0 0-4.252 4.054l-.987-.987a2 2 0 0 0-2.828 2.828l2.5 2.5a2 2 0 0 0 2.95-.134l.056-.066a40.007 40.007 0 0 1 5.122-5.122zM4 7a3 3 0 0 1 3-3h10a3 3 0 0 1 3 3v10a3 3 0 0 1-3 3H7a3 3 0 0 1-3-3V7z",stroke:"currentColor",strokeWidth:2})]}))}u.displayName=u.name+" [from "+i.id+"]",u._isSVG=!0;var c=u;l.default=c}),98);
__d("MetaBrandSquareOpenFilled24Icon.react",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react"));function u(e){return s.jsxs("svg",babelHelpers.extends({viewBox:"0 0 24 24",fill:"currentColor",width:"1em",height:"1em"},e,{children:[e.title!=null&&s.jsx("title",{children:e.title}),e.children!=null&&s.jsx("defs",{children:e.children}),s.jsx("path",{fillRule:"evenodd",clipRule:"evenodd",d:"M19 17V7a2 2 0 0 0-2-2H7a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2zM7 3a4 4 0 0 0-4 4v10a4 4 0 0 0 4 4h10a4 4 0 0 0 4-4V7a4 4 0 0 0-4-4H7z"})]}))}u.displayName=u.name+" [from "+i.id+"]",u._isSVG=!0;var c=u;l.default=c}),98);
__d("configCache",[],(function(t,n,r,o,a,i){"use strict";var e=null;function l(){return e}function s(t){e=t}function u(t){return function(n,r){e=null,t(n,r)}}i.getConfigCache=l,i.setConfigCache=s,i.wrapOnClose=u}),66);